name: Backup Bluesky posts

on:
  push:
  schedule:
    # At minute 4 past every 4th hour
    # https://crontab.guru/#4_*/4_*_*_*
    - cron: '4 */4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up secrets
      - name: Set environment variables
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}

      # Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.6"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # Set up Python environment using uv
      - name: Set up Python
        run: uv python install

      # Install project dependencies
      - name: Install the project
        run: uv sync

      # Run the backup script
      - name: Backup new posts
        run: uv run python backup_posts.py

      # Commit changes to the database file
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Backup new posts
          file_pattern: '*.db'
